#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "WXReport"
  https://create.arduino.cc/cloud/things/8c6238ec-31f7-4b77-8f14-54bf44a9ff8f

  Arduino IoT Cloud Properties description

  The following variables are automatically generated and updated when changes are made to the Thing properties

  String qNH;
  float uVIndex;
  float illuminance;
  float dewPoint;
  float temperature;

  Properties which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Arduino_MKRENV.h>

double fieldElev = 30; // field elevation in ft

float dPoint(float temperature, float relativeHumidity) {
  float a = 6.112;
  float b = 17.67;
  float c = 243.5;
  float g = log(relativeHumidity / 100) + (b * temperature / (c + temperature));
  return c * g / (b - g);
  }

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);
  if (!ENV.begin()) {
    Serial.println("Failed to initialize MKR ENV shield!");
    while (1);
  }

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}


void loop() {
  ArduinoCloud.update();
  temperature = ENV.readTemperature();
  float humidity = ENV.readHumidity();
  dewPoint = dPoint(temperature, humidity);
  float pressure = ENV.readPressure(MILLIBAR);
  illuminance = float(ENV.readIlluminance());
  uVIndex = float(ENV.readUVIndex());
  float qnh_raw = (pressure - 0.3) * pow(1 + 0.00002567294033 * fieldElev / pow(pressure - 0.3, 0.190284), 1 / 0.190284);
  float alt = 2.95300 * qnh_raw;
  if (qnh_raw < 1000) {
     qNH = "Q0" + String(round(qnh_raw)) + "/A" + String(round(alt));
  } else {
     qNH = "Q" + String(round(qnh_raw)) + "/A" + String(round(alt)); 
  }
}
