#define SECRET_SSID "MySpectrumWiFiAB-2G"
#define SECRET_PASS "domainmarket073"
#define SECRET_BOT_TOKEN "1184285211:AAEKwi0fNapheppl2ie6cI3tGSsVTC8egv4"
#define SECRET_BOT_NAME "cat_food"
#define SECRET_BOT_USERNAME "cat_food_bot"
